name: Bug Report
description: Report an issue with supported versions of Musket Mod
labels: ["bug"]
body:
  - type: markdown
    id: md-description
    attributes:
      value: "Please enter the following contents"
  - type: input
    id: mc-version
    attributes:
      label: Minecraft version
      placeholder: eg. 1.20.1
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod loader you are using
      options:
        - Forge
        - Fabric
        - Neoforge
        - Quilt
        - LiteLoader
        - Other (describe below)
      multiple : true
    validations :
      required : true
  - type: input
    id: mod-version
    attributes:
      label: Musket Mod version
      placeholder: eg. musketmod-1.20.1-fabric-1.5.1
    validations:
      required: true
  - type: textarea
    id: modList
    attributes:
      label: Modpack info or mod list
      description: If playing a modpack, post the link to it!
    validations:
      required: true
  - type: input
    id: log-file
    attributes:
      label: "The latest.log file and hs_err_pidXXX if exists"
      description: "Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc."
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce (if reproducing the issue requires exact steps)
      placeholder: |
        1. First step
        2. Second step
        3. etc...
